function [fitresult, gof] = createFit1(Vrpm, fc)
%CREATEFIT1(VRPM,FC)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : Vrpm
%      Y Output: fc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Apr-2020 15:46:21


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( Vrpm, fc );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'fc vs. Vrpm', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Vrpm', 'Interpreter', 'none' );
ylabel( 'fc', 'Interpreter', 'none' );
grid on


