function [fitresult, gof] = createFit(fc, Vrpm)
%CREATEFIT(FC,VRPM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fc
%      Y Output: Vrpm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Apr-2020 15:24:35


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fc, Vrpm );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Vrpm vs. fc', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'fc', 'Interpreter', 'none' );
ylabel( 'Vrpm', 'Interpreter', 'none' );
grid on


